name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '1 5 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl -L "https://www.stlouis-mo.gov/customcf/endpoints/occupancy-permits/occupancy-permits-30-days-export.cfm?permitType=all&dataType=json" | jq 'sort_by(.ISSUEDATE, .ADDRESS) | reverse[]' > permits.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push

